name: createGhPages
on: [push]

jobs:
  TEST:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: peaceiris/actions-hugo@v2
      
      # - run: sed -i  -e 's_baseURL = "https://f3.anthus.ir/"_baseURL = "https://pipitsong.github.io/"_g' config.toml
      # - run: sed -i  -e 's_baseURL = "https://f3.anthus.ir/"_baseURL = "https://f4.anthus.ir/"_g' config.toml
      - run: hugo -D --config config.toml,config-git.toml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          mv -f public/ /tmp/
